### ISSUE TITLE
How to change serving path from `/SOGo` to `/`?

### ISSUE THREAD

**Issue by NiklasRosenstein** [sonroyaalmerol/docker-sogo#17]
Hi! Thanks a lot for this project, I'm giving it a try on my Kubernetes cluster.

May I ask, how can I change the path that the SOGo app can be visited from `/SOGo` to `/`? 

My Helm values are

```yaml
ingress:
  enabled: true
  className: nginx-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
  - hosts: [sogo.example.com]
    secretName: sogo-tls
sogo:
  host: sogo.example.com
  configs:
    SOGoTimeZone: Europe/Berlin
  secrets:
    SOGoProfileURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_user_profile'
    OCSFolderInfoURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_folder_info'
    OCSSessionsFolderURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_sessions_folder'
    OCSCacheFolderURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_cache_folder'
    OCSStoreURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_store'
    OCSAclURL: '${{ b64decode(lookup("v1", "Secret", "sogo-db-app", "sogo").data.uri) }}/sogo_acl'
```
